<a href="https://colab.research.google.com/github/Voland24/ModernComputerVisionPytorch/blob/main/PytorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np
x = torch.tensor([[1,2]])
y = torch.tensor([[1], [2]])
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([2, 1])


Torch automatically converts all the data in a tensor in its most general form. Since all its data must be the same type

In [3]:
x = torch.tensor([False, 1, 10, 2.0])
print(x)
print(x.shape)

tensor([ 0.,  1., 10.,  2.])
torch.Size([4])


Different ways to init a tensor

In [8]:
torch.zeros((3,4))
torch.ones((3,4))
torch.randint(low = 0, high = 10, size = (3,4)) #without the 10
torch.rand(3,4) #rand numbers from 0 to 1

x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
(2, 3)
torch.Size([2, 3])


**Operations on tensors**

In [21]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
print( x * 10)
y = x.add(10)
print(y)

#rehsape
print("RESHAPE")
y = torch.randint(low = 1, high = 11, size = (4,1))
print(y)

y = y.view(1,4)
print(y)

#squeeze, removing dim size of 1, for a given axis
print("SQUEEZE")
x = torch.randn(10,1,10) #rand from 0 - 1 in shape (10,1,10)
print(x.shape)

y = torch.squeeze(x,1) #1 here means in the 2nd dim
z = x.squeeze(1)

assert torch.all(y == z)
print(z.shape)
print(y.shape)


#unsqueeze means the opposite, we add a dim where we specify
print("UNSQUEEZE")
x = torch.randn(10,10)
print(x.shape)

y = x.unsqueeze(0)
print(y.shape)

#we can also do this with None

x = torch.randn(10,10)
y1, y2, y3 = x[None], x[:None], x[:,:,None]
print("WITH NONE")
print(y1.shape)
print(y2.shape)
print(y3.shape)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])
tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])
RESHAPE
tensor([[9],
        [1],
        [5],
        [8]])
tensor([[9, 1, 5, 8]])
SQUEEZE
torch.Size([10, 1, 10])
torch.Size([10, 10])
torch.Size([10, 10])
UNSQUEEZE
torch.Size([10, 10])
torch.Size([1, 10, 10])
WITH NONE
torch.Size([1, 10, 10])
torch.Size([10, 10])
torch.Size([10, 10, 1])


#**Multiplication ops on tensors**

In [31]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
y = torch.tensor([[10,11,12,13]])
print("MULTIPLYING")
print(x.shape)
print(y.shape)
print(torch.matmul(x, y.T))
print(torch.matmul(x, y.T).shape)


#We can also achieve this with the @ operator

print(x@y.T)

#we can concatenate two tensors
print("CONCAT")
x = torch.randn(10,10)
y = torch.cat([x,x], axis = 0)
z = torch.cat([x,x], axis = 1)
print(f"x shape {x.shape} y shape {y.shape}") #added more rows
print(f"z shape {z.shape}") #added more columns

MULTIPLYING
torch.Size([2, 4])
torch.Size([1, 4])
tensor([[120],
        [304]])
torch.Size([2, 1])
tensor([[120],
        [304]])
CONCAT
x shape torch.Size([10, 10]) y shape torch.Size([20, 10])
z shape torch.Size([10, 20])


#**Max and min values**

In [37]:
x = torch.arange(25).reshape(5,5)
print(x)
print(x.shape)
print(x.max())
print(x.max(dim = 0)) #the row with the highest values
print(x.max(dim = 1)) #the column with the highest values

#the min operator behaves exactly the same


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
torch.Size([5, 5])
tensor(24)
torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))
torch.return_types.max(
values=tensor([ 4,  9, 14, 19, 24]),
indices=tensor([4, 4, 4, 4, 4]))


In [39]:
#We can also permute the dims of a tensor

x = torch.randn(10,20,30)
y = x.permute(2,0,1)
print(y.shape)


#use view to reshape the tensor and permute if we need to permute its dims, NEVER use view for permuting

torch.Size([30, 10, 20])
